### ISSUE TITLE
NCMBUserService構成変更

### ISSUE THREAD

**Issue by kobo0908** [NIFCLOUD-mbaas/ncmb_kotlin#16]
### 概要

- NCMBUserServiceの継承先をNCMBObject->NCMBObjectService変更
- NCMBUserServiceにてreflectResponceを実施するように変更
- NCMBUserServiceで独自で行なっている処理をNCMBObjectServiceの処理をoverrideできないか 

### 参考

https://github.com/NIFCLOUD-mbaas/ncmb_android/blob/master/ncmb-core/src/main/java/com/nifcloud/mbaas/core/NCMBUserService.java

**Comment by thuydg** [comment]
本件こちらのバージョンで対応したため、クローズいたします
https://github.com/NIFCLOUD-mbaas/ncmb_kotlin/releases/tag/v0.2.0
