### ISSUE TITLE
データストアのクエリ機能の基本追加

### ISSUE THREAD

**Issue by ncmbadmin** [NIFCLOUD-mbaas/ncmb_kotlin#21]
### データストア検索機能の利用インターフェイス検討

* 基本使い方のイメージ

```kotlin
        val query = NCMBQuery.forObject("TestClass")
        query.whereEqualTo("KeyString", "a")
        query.findInBackground (NCMBCallback { e, objects ->
            if (e != null) {
                //エラー時の処理
                println( "検索に失敗しました。エラー:" + e.message)
            } else {
                //成功時の処理
                println("検索に成功しました。")
                if(objects is List<*>) {
                    for (obj:Any? in objects) {
                        if (obj is NCMBObject) {
                            println(obj.getObjectId())
                        }
                    }
                }
            }
        })
```

* v0.2.0で対応した機能（詳細はREADMEにて利用サンプルをご確認ください）
  - find()  
  - findInBackground()
  - count()
  - countInBackground()
  - 検索条件
     - whereEqualTo
     - whereNotEqualTo
     - whereLessThan
     - whereGreaterThan
     - whereLessThanOrEqualTo
     - whereGreaterThanOrEqualTo
     - whereContainedIn
     - whereNotContainedIn
     - whereContainedInArray
     - whereNotContainedInArray
     - Limit
     - skip
     - addOrderByAscending
     - addOrderByDescending

**Comment by thuydg** [comment]
本件こちらのバージョンで対応したため、クローズいたします
https://github.com/NIFCLOUD-mbaas/ncmb_kotlin/releases/tag/v0.2.0
