### ISSUE TITLE
NCMBQuery実行時にフィールドデータが取得できません

### ISSUE THREAD

**Issue by goofmint** [NIFCLOUD-mbaas/ncmb_kotlin#50]
v0.2.0でのフィードバックです。

NCMBQueryを使った際、NCMBObjectのreflectResponseを実行しているでしょうか？恐らく実行していないため、this.keysが空のままで、フィールドデータが取れなくなっています。NCMBObjectのfetch/fetchInBackgroundを使った場合には取得できます。

こちら this.keys はそもそも不要ではないでしょうか？mFieldsを直接見た方が確実に思えます。

**Comment by ncmbadmin** [comment]
@goofmint  様

お世話になっております。
本 issue の 改修が完了し v1.0.0 にてリリース済みです。
ご報告ありがとうございました。
改修済みのSDKは以下のリリースページにてご確認ください。
https://github.com/NIFCLOUD-mbaas/ncmb_kotlin/releases

ご確認いただき、問題なければissueをクローズいただけますでしょうか。
今後とも、どうぞよろしくお願いいたします。

**Comment by ncmbadmin** [comment]
お世話になっております。本件対応完了しましたので、issueをクローズさせていただきます。
不明点などありましたら、こちらにコメントいただければと思います。
